/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.eomcs.lms;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
  public static void main(String[] args) {
    System.out.println("수업 관리 시스템입니다.");
  }
}
